Use `update_idletasks()` to avoid hangs on epar GUI window.
iraf-community/pyraf pull request #145
Opened 2022-10-19 18:20 UTC by monodera

Apparently using `update()` for tkinter objects hang the process when `epar` is executed in pyraf. Using `update_idletasks()` appears to fix it.

This is a possible fix for #144

I added `# isort: skip` to avoid auto-formatting with my editor (I couldn't disable it, sorry). Please ignore these changes.

2022-10-19 18:29 UTC, olebole requested changes

2022-10-19 18:29 UTC, olebole commented on pyraf/tools/editpar.py
> +from . import basicpar, eparoption, irafutils, taskpars # isort: skip
Could you remove the ` # isort: skip` additions here?

2022-10-19 18:29 UTC, olebole commented on pyraf/tools/editpar.py
> +            from . import filedlg # isort: skip
and also here?

2022-10-19 18:44 UTC, monodera commented
I edited it directly on GitHub. Hope it works (I'm not get used to the github workflow).

2022-10-20 18:41 UTC, olebole commented
I can confirm that this works on Linux (Debian testing) as well. So, I will merge.

Thank you very much for this finding and the PR!

2022-10-20 18:41 UTC, merged